import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();


  const [formData, setFormData] = useState({
    firstName: "",
    userName: ""
  })

  const CheckLogin = () => {
    console.log(formData.firstName)
    console.log(formData)

    if (formData.userName !== null) {
      router.push({
        pathname: './counter',
        query: {
          userName: formData.userName
        }
      })
    }

  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <label> First Name:</label>
        <input
          type="text"
          id="firstName"
          name='firstName'
          pattern="[A-Z] {1} [a-z] {2, 10}"
          title='The first letter should be capital'
          onChange={(e => setFormData({ ...formData, firstName: e.target.value }))}
        />

        <label> Username:</label>
        <input
          type="text"
          id="userName"
          name='userName'
          required
          title='The first letter should be capital'
          minLength="5"
          maxLength="10"
          onChange={(e => setFormData({ ...formData, userName: e.target.value }))}
        />

        <button type='submit' onClick={() => CheckLogin()}>Sumbit</button>
      </main>
    </>
  )
}
